language: c
compiler:
  - gcc
  - clang
env:
  - C99_SOURCE=""
  - 
  - USE_XFT=0
matrix:
  exclude:
    - compiler: clang
      env: C99_SOURCE=""
before_install: sudo apt-get install lua5.2 liblua5.2-dev gettext
script:
  - make
  - make test
